This is setting up the import package for data pre-processing

In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive

Add the datasets to your Google Drive using the links above, then mount your Drive to the notebook by running the cell below.

In [ ]:
prefix = '/content/drive'
from google.colab import drive
drive.mount(prefix, force_remount=True)

Mounted at /content/drive

We will pull the zipcode file to collect all zipcode in a set

In [ ]:
zip_path = '/content/drive/MyDrive/CIS550_Project/clean_zip_with_P.csv' # Path to life expectancy dataset in your drive

In [ ]:
zip_d = pd.read_csv(zip_path)
zip_d['ZipCode'] = zip_d['ZipCode'].astype(str)
zip_d['ZipCode'] = zip_d['ZipCode'].str.zfill(5)
zip_d['Population'] = zip_d['Population'].astype('Int64')
zip_d

      ZipCode  Latitude  Longitude         City State  Population
0       00501     40.81     -73.04   Holtsville    NY        <NA>
1       00544     40.81     -73.04   Holtsville    NY        <NA>
2       00601     18.16     -66.72     Adjuntas    PR       17242
3       00602     18.38     -67.18       Aguada    PR       37548
4       00603     18.43     -67.15    Aguadilla    PR       49804
...       ...       ...        ...          ...   ...         ...
42730   99926     55.14    -131.49   Metlakatla    AK        1562
42731   99927     56.33    -133.61  Point Baker    AK          49
42732   99928     55.45    -131.79    Ward Cove    AK        <NA>
42733   99929     56.41    -131.61     Wrangell    AK        2079
42734   99950     55.34    -131.64    Ketchikan    AK        <NA>

[42735 rows x 6 columns]

In [ ]:
zip_d

      ZipCode  Latitude  Longitude         City State  Population
0       00501     40.81     -73.04   Holtsville    NY        <NA>
1       00544     40.81     -73.04   Holtsville    NY        <NA>
2       00601     18.16     -66.72     Adjuntas    PR       17242
3       00602     18.38     -67.18       Aguada    PR       37548
4       00603     18.43     -67.15    Aguadilla    PR       49804
...       ...       ...        ...          ...   ...         ...
42730   99926     55.14    -131.49   Metlakatla    AK        1562
42731   99927     56.33    -133.61  Point Baker    AK          49
42732   99928     55.45    -131.79    Ward Cove    AK        <NA>
42733   99929     56.41    -131.61     Wrangell    AK        2079
42734   99950     55.34    -131.64    Ketchikan    AK        <NA>

[42735 rows x 6 columns]

Create a set containing all the zipCode

In [ ]:
zip_set = set(zip_d["ZipCode"])

In [ ]:
zip_d.to_csv('/content/drive/MyDrive/CIS550_Project/06_30/post/clean_zipcode_with_population.csv', index=False)

ChildCare complete

In [ ]:
childc_path = '/content/drive/MyDrive/CIS550_Project/06_30/pre/clean_childcare.csv' # Path to life expectancy dataset in your drive

In [ ]:
child_c = pd.read_csv(childc_path)
child_c['ZipCode'] = child_c['ZipCode'].astype(str)
child_c['ZipCode'] = child_c['ZipCode'].str.zfill(5)
#zip_d['Population'] = zip_d['Population'].astype('Int64')
child_c

            Id ZipCode   Longitude   Latitude
0            0   99883 -132.942929  56.810693
1            1   99645 -149.124956  61.598242
2            2   99654 -149.597261  61.533559
3            3   99654 -149.327400  61.614910
4            4   99508 -149.782500  61.192540
...        ...     ...         ...        ...
132212  132212   58501 -100.788500  46.816000
132213  132213   67501  -97.925990  38.041730
132214  132214   66616  -95.649090  39.059140
132215  132215   66617  -95.664890  39.123580
132216  132216   66720  -95.470290  37.666830

[132217 rows x 4 columns]

In [ ]:
child_c = child_c[child_c['ZipCode'].isin(zip_set)]
child_c

            Id ZipCode   Longitude   Latitude
1            1   99645 -149.124956  61.598242
2            2   99654 -149.597261  61.533559
3            3   99654 -149.327400  61.614910
4            4   99508 -149.782500  61.192540
5            5   99611 -151.245825  60.557807
...        ...     ...         ...        ...
132212  132212   58501 -100.788500  46.816000
132213  132213   67501  -97.925990  38.041730
132214  132214   66616  -95.649090  39.059140
132215  132215   66617  -95.664890  39.123580
132216  132216   66720  -95.470290  37.666830

[132165 rows x 4 columns]

In [ ]:
child_c.to_csv('/content/drive/MyDrive/CIS550_Project/06_30/post/clean_childcare.csv', index=False)

No need to do it for clean city

Clean FireFighter Check

In [ ]:
ff_path = '/content/drive/MyDrive/CIS550_Project/06_30/pre/clean_firefighter.csv' # Path to life expectancy dataset in your drive
ff = pd.read_csv(ff_path)
ff

       DeptId  ZipCode  NumberOfStations  ActivePersonnel
0           0    74432                 1               15
1           1    72537                 2               29
2           2     1085                 1               30
3           3    74647                 1                8
4           4    65793                 3               37
...       ...      ...               ...              ...
27082   27082    44697                 1               14
27083   27083    40165                 2               40
27084   27084    55991                 1               23
27085   27085    55992                 1               30
27086   27086    87327                 2               26

[27087 rows x 4 columns]

In [ ]:
ff_path = '/content/drive/MyDrive/CIS550_Project/06_30/pre/clean_firefighter.csv' # Path to life expectancy dataset in your drive
ff = pd.read_csv(ff_path)
ff['ZipCode'] = ff['ZipCode'].astype(str)
ff['ZipCode'] = ff['ZipCode'].str.zfill(5)
ff = ff[ff['ZipCode'].isin(zip_set)]
ff

       DeptId ZipCode  NumberOfStations  ActivePersonnel
0           0   74432                 1               15
1           1   72537                 2               29
2           2   01085                 1               30
3           3   74647                 1                8
4           4   65793                 3               37
...       ...     ...               ...              ...
27082   27082   44697                 1               14
27083   27083   40165                 2               40
27084   27084   55991                 1               23
27085   27085   55992                 1               30
27086   27086   87327                 2               26

[27071 rows x 4 columns]

In [ ]:
ff.to_csv('/content/drive/MyDrive/CIS550_Project/06_30/post/clean_firefighter.csv', index=False)

Health Measure check

In [ ]:
hm_path = '/content/drive/MyDrive/CIS550_Project/06_30/pre/clean_healthmeasure.csv' # Path to life expectancy dataset in your drive
hm = pd.read_csv(hm_path)
hm

,Measure,ZipCode,Ratio,TotalPopulation
0,Obesity among adults,77489,0.447,37257
1,Current asthma among adults,77493,0.088,51774
2,Visits to doctor for routine checkup within th...,77493,0.720,51774
3,Depression among adults,77493,0.208,51774
4,Housing insecurity in the past 12 months among...,77493,0.166,51774
...,...,...,...,...
177881,Current asthma among adults,77489,0.110,37257
177882,Visits to doctor for routine checkup within th...,77489,0.789,37257
177883,Depression among adults,77489,0.185,37257
177884,Housing insecurity in the past 12 months among...,77489,0.223,37257
177885,Feeling socially isolated among adults,77489,0.354,37257

In [ ]:
hm_path = '/content/drive/MyDrive/CIS550_Project/06_30/pre/clean_healthmeasure.csv'
hm = pd.read_csv(hm_path)
hm['ZipCode'] = hm['ZipCode'].astype(str)
hm['ZipCode'] = hm['ZipCode'].str.zfill(5)
hm = hm[hm['ZipCode'].isin(zip_set)]
hm

,Measure,ZipCode,Ratio,TotalPopulation
0,Obesity among adults,77489,0.447,37257
1,Current asthma among adults,77493,0.088,51774
2,Visits to doctor for routine checkup within th...,77493,0.720,51774
3,Depression among adults,77493,0.208,51774
4,Housing insecurity in the past 12 months among...,77493,0.166,51774
...,...,...,...,...
177881,Current asthma among adults,77489,0.110,37257
177882,Visits to doctor for routine checkup within th...,77489,0.789,37257
177883,Depression among adults,77489,0.185,37257
177884,Housing insecurity in the past 12 months among...,77489,0.223,37257
177885,Feeling socially isolated among adults,77489,0.354,37257

In [ ]:
hm.to_csv('/content/drive/MyDrive/CIS550_Project/06_30/post/clean_healthmeasure.csv', index=False)

Hospital

In [ ]:
ho_path = '/content/drive/MyDrive/CIS550_Project/06_30/pre/clean_hospital.csv' # Path to life expectancy dataset in your drive
ho = pd.read_csv(ho_path)
ho

,Id,ZipCode,Longitude,Latitude,NumberOfBeds,TraumaLevel,HasHelipad
0,8237,36420,-86.494549,31.295795,88,3.0,True
1,8238,35611,-86.978407,34.804164,71,3.0,False
2,8239,36502,-87.478799,31.017024,51,3.0,True
3,8240,36117,-86.174930,32.376399,150,NaN,True
4,8241,36111,-86.277549,32.328154,432,2.0,True
...,...,...,...,...,...,...,...
8335,16572,34119,-81.689027,26.248655,50,NaN,False
8336,16573,48235,-83.181846,42.418797,383,NaN,True
8337,16574,48236,-82.914367,42.420058,654,NaN,True
8338,16575,85301,-114.438263,32.860033,0,NaN,False
8339,16576,92078,-117.170294,33.129542,168,NaN,False

In [ ]:
ho_path = '/content/drive/MyDrive/CIS550_Project/06_30/pre/clean_hospital.csv'
ho = pd.read_csv(ho_path)
ho['ZipCode'] = ho['ZipCode'].astype(str)
ho['ZipCode'] = ho['ZipCode'].str.zfill(5)
ho = ho[ho['ZipCode'].isin(zip_set)]
ho

,Id,ZipCode,Longitude,Latitude,NumberOfBeds,TraumaLevel,HasHelipad
0,8237,36420,-86.494549,31.295795,88,3.0,True
1,8238,35611,-86.978407,34.804164,71,3.0,False
2,8239,36502,-87.478799,31.017024,51,3.0,True
3,8240,36117,-86.174930,32.376399,150,NaN,True
4,8241,36111,-86.277549,32.328154,432,2.0,True
...,...,...,...,...,...,...,...
8335,16572,34119,-81.689027,26.248655,50,NaN,False
8336,16573,48235,-83.181846,42.418797,383,NaN,True
8337,16574,48236,-82.914367,42.420058,654,NaN,True
8338,16575,85301,-114.438263,32.860033,0,NaN,False
8339,16576,92078,-117.170294,33.129542,168,NaN,False

In [ ]:
ho.to_csv('/content/drive/MyDrive/CIS550_Project/06_30/post/clean_hospital.csv', index=False)

Mean_Income Check

In [ ]:
mi_path = '/content/drive/MyDrive/CIS550_Project/06_30/pre/clean_mean_income.csv' # Path to life expectancy dataset in your drive
mi = pd.read_csv(mi_path)
mi

                GeoID  ZipCode  MeanIncome
0      860Z200US00601      601     24781.0
1      860Z200US00602      602     30378.0
2      860Z200US00603      603     32478.0
3      860Z200US00606      606     25125.0
4      860Z200US00610      610     34513.0
...               ...      ...         ...
33767  860Z200US99923    99923         NaN
33768  860Z200US99925    99925     96344.0
33769  860Z200US99926    99926     83973.0
33770  860Z200US99927    99927         NaN
33771  860Z200US99929    99929     81514.0

[33772 rows x 3 columns]

In [ ]:
mi_path = '/content/drive/MyDrive/CIS550_Project/06_30/pre/clean_mean_income.csv' # Path to life expectancy dataset in your drive
mi = pd.read_csv(mi_path)
mi['ZipCode'] = mi['ZipCode'].astype(str)
mi['ZipCode'] = mi['ZipCode'].str.zfill(5)
mi = mi[mi['ZipCode'].isin(zip_set)]
mi

                GeoID ZipCode  MeanIncome
0      860Z200US00601   00601     24781.0
1      860Z200US00602   00602     30378.0
2      860Z200US00603   00603     32478.0
3      860Z200US00606   00606     25125.0
4      860Z200US00610   00610     34513.0
...               ...     ...         ...
33767  860Z200US99923   99923         NaN
33768  860Z200US99925   99925     96344.0
33769  860Z200US99926   99926     83973.0
33770  860Z200US99927   99927         NaN
33771  860Z200US99929   99929     81514.0

[33772 rows x 3 columns]

In [ ]:
mi.to_csv('/content/drive/MyDrive/CIS550_Project/06_30/post/clean_mean_income.csv', index=False)

Police Check

In [ ]:
pp_path = '/content/drive/MyDrive/CIS550_Project/06_30/pre/clean_police.csv' # Path to life expectancy dataset in your drive
pp = pd.read_csv(pp_path)
pp

,Id,ZipCode,Longitude,Latitude,FullTimeOfficers,PartTimeOfficers,TotalActiveOfficers
0,1,30141,-84.760902,33.875780,15.0,0.0,15.0
1,2,30427,-81.930495,31.935284,8.0,3.0,11.0
2,3,71369,-91.810631,30.986499,7.0,3.0,10.0
3,4,71024,-93.238851,32.541204,1.0,0.0,1.0
4,5,48759,-83.453271,43.732038,3.0,14.0,17.0
...,...,...,...,...,...,...,...
23481,23654,30236,-84.354413,33.517138,24.0,5.0,29.0
23482,23655,30117,-85.076456,33.577741,64.0,0.0,64.0
23483,23656,30185,-84.915831,33.496243,5.0,2.0,7.0
23484,23657,30742,-85.245958,34.950209,32.0,2.0,34.0
23485,23658,30736,-85.108432,34.917299,8.0,1.0,9.0

In [ ]:
pp_path = '/content/drive/MyDrive/CIS550_Project/06_30/pre/clean_police.csv' # Path to life expectancy dataset in your drive
pp = pd.read_csv(pp_path)
pp['ZipCode'] = pp['ZipCode'].astype(str)
pp['ZipCode'] = pp['ZipCode'].str.zfill(5)
pp['FullTimeOfficers'] = pp['FullTimeOfficers'].astype('Int64')
pp['PartTimeOfficers'] = pp['PartTimeOfficers'].astype('Int64')
pp['TotalActiveOfficers'] = pp['TotalActiveOfficers'].astype('Int64')
pp = pp[pp['ZipCode'].isin(zip_set)]
pp

,Id,ZipCode,Longitude,Latitude,FullTimeOfficers,PartTimeOfficers,TotalActiveOfficers
0,1,30141,-84.760902,33.875780,15,0,15
1,2,30427,-81.930495,31.935284,8,3,11
2,3,71369,-91.810631,30.986499,7,3,10
3,4,71024,-93.238851,32.541204,1,0,1
4,5,48759,-83.453271,43.732038,3,14,17
...,...,...,...,...,...,...,...
23481,23654,30236,-84.354413,33.517138,24,5,29
23482,23655,30117,-85.076456,33.577741,64,0,64
23483,23656,30185,-84.915831,33.496243,5,2,7
23484,23657,30742,-85.245958,34.950209,32,2,34
23485,23658,30736,-85.108432,34.917299,8,1,9

In [ ]:
pp.to_csv('/content/drive/MyDrive/CIS550_Project/06_30/post/clean_police.csv', index=False)

Realtor Check

In [ ]:
rr_path = '/content/drive/MyDrive/CIS550_Project/06_30/pre/clean_realtor.csv' # Path to life expectancy dataset in your drive
rr = pd.read_csv(rr_path)
rr

         MonthDate  ZipCode  MedianListingPrice  ActiveListingCount
0           202504    28557            472450.0                65.0
1           202504    48602             84925.0                59.0
2           202504    53714            364925.0                 7.0
3           202504    12838            118625.0                 1.0
4           202504    85654            250000.0                 1.0
...            ...      ...                 ...                 ...
2999225     201607    74074            219000.0               101.0
2999226     201607    63109            155000.0               106.0
2999227     201607    54113            164944.0                22.0
2999228     201607     7059            899900.0               117.0
2999229     201607    35128            284000.0                82.0

[2999230 rows x 4 columns]

In [ ]:
rr_path = '/content/drive/MyDrive/CIS550_Project/06_30/pre/clean_realtor.csv' # Path to life expectancy dataset in your drive
rr = pd.read_csv(rr_path)
rr['ZipCode'] = rr['ZipCode'].astype(str)
rr['ZipCode'] = rr['ZipCode'].str.zfill(5)
rr['MedianListingPrice'] = rr['MedianListingPrice'].astype('Int64')
rr['ActiveListingCount'] = rr['ActiveListingCount'].astype('Int64')
rr = rr[rr['ZipCode'].isin(zip_set)]
rr

         MonthDate ZipCode  MedianListingPrice  ActiveListingCount
0           202504   28557              472450                  65
1           202504   48602               84925                  59
2           202504   53714              364925                   7
3           202504   12838              118625                   1
4           202504   85654              250000                   1
...            ...     ...                 ...                 ...
2999225     201607   74074              219000                 101
2999226     201607   63109              155000                 106
2999227     201607   54113              164944                  22
2999228     201607   07059              899900                 117
2999229     201607   35128              284000                  82

[2999208 rows x 4 columns]

In [ ]:
rr.to_csv('/content/drive/MyDrive/CIS550_Project/06_30/post/clean_realtor.csv', index=False)